# This workflow will do a clean install of quasar CLI and its dependencies, build the source code and drafts a release
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Name of the workflow
name: Node.js Quasar CI

# Trigger workflow on push and pull request to master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout master branch
      uses: actions/checkout@latest
    # If package.json contains higher version, create tag
    - name: Create release tag
      id: autotag
      uses: Klemensas/action-autotag@latest
      with:
        tag_prefix: "v"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    # If previous step created tag, draft release
    - name: Draft Release
      id: draft_release
      if: ${{ steps.autotag.outputs.tagname }} # if no tag was created, skip creating draft
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.autotag.outputs.tagname }}
        release_name: Release ${{ steps.autotag.outputs.tagname }}
        body: |
          # Changelog
          - TODO
        draft: true
        prerelease: true
    # Install yarn, quasar CLI, install depedencies and build and publish if tag and draft was created
    - name: Use Node.js Quasar CLI
      uses: actions/setup-node@latest
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - run: yarn global add @quasar/cli
    - run: yarn
    - run: yarn release
